all: make run clear

make: grafoSimples_MatrizAdj.c
	cl grafoSimples_MatrizAdj.c
run: grafoSimples_MatrizAdj.obj
	grafoSimples_MatrizAdj.exe
clear:
	del grafoSimples_MatrizAdj.exe grafoSimples_MatrizAdj.obj